import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import kiran from "../public/business-kiran.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-zinc-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-3xl">Kiran</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-zinc-600 text- to-gray-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/147juthUr3vE0SEEZ1mLP3wFyiSWMHdnp/view?usp=sharing"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-4xl mt-5 py-2 text-black font-medium dark:text-white md:text-5xl">
              Hi, I'm <span className="text-teal-500 ">Kiran</span>
            </h2>
            <h3 className="text-3xl py-2 dark:text-white md:text-4xl">
              Full Stack Developer.
            </h3>
            <p className="text-md py-3 leading-8 text-gray-800 dark:text-gray-400 max-w-3xl mx-auto md:text-xl">
            As an ambitious Full Stack Developer, my expertise lies in both front-end and back-end development. 
            As a motivated and skilled Full Stack Developer, I have a strong foundation in front-end technologies 
            such as HTML, CSS, React.js, JavaScript, and Tailwind CSS. In addition, I possess expertise in back-end 
            development using Node.js, Postman, AWS Services such as Lambda, DynamoDB, API Gateway, Cloud9, Cloudwatch, and CodeCommit.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://twitter.com/HeggeKiran"><AiFillTwitterCircle /></a>
              <a href="https://www.linkedin.com/in/kiran-kumar-hegge-595568234/"><AiFillLinkedin /></a>
              <a href="https://github.com/Kirankumarhegge"><AiFillGithub /></a>
              
            </div>
          </div>
        </section>
        <section>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-zinc-700 dark:text-white flex-1">
              <Image src={design} width={90} height={90} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Front-End Skills
              </h3>
              <p className="py-2">
                Creating elegant front-end websites for better user experience. 
              </p>
              <h4 className="py-4 text-teal-500">Front-End Tools I Use</h4>
              <p className="py-1">React.js</p>
              <p className="py-1">HTML</p>
              <p className="py-1">CSS</p>
              <p className="py-1">Tailwind</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-zinc-700 dark:text-white flex-1">
              <Image src={code} width={90} height={90} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Back-End Skills
              </h3>
              <p className="py-2">
                Creating a fully functional and dynamic back-end website.
              </p>
              <h4 className="py-4 text-teal-500">Back-End Tools I Use</h4>
              <p className="py-1">Node.js</p>
              <p className="py-1">AWS</p>
              <p className="py-1">SQL</p>
              <p className="py-1">Postman</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-zinc-700 dark:text-white flex-1">
              <Image src={consulting} width={80} height={80} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-500">Additional Tools I Use</h4>
              <p className="py-1">Next.js</p>
              <p className="py-1">Bootstrap</p>
              <p className="py-1">Material UI</p>
              <p className="py-1">Chakra UI</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Projects</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              
              As a passionate and driven 
              <span className="text-teal-500"> Web developer</span>
              , I have embarked on a journey to gain practical experience in both front-end and back-end development. 
              Through various projects, <span className="text-teal-500"> I have honed my skills in JavaScript, 
              front-end technologies like React.js, HTML, CSS, 
              and back-end technologies like Node.js and AWS, SQL. </span>
              To get a glimpse of my work, please click on the accompanying image. 
              I am eager to contribute my knowledge and continue learning in a professional environment.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap ">
            <div className="basis-1/3 flex-1">
            <a href="https://kirankumarhegge.github.io/ignite/">
                <Image
                  className="rounded-lg object-cover"
                  width={"90%"}
                  height={"70%"}
                  layout="responsive"
                  src={web1}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://634b87b56fb74630e4818dfb--statuesque-dolphin-0a7e25.netlify.app/">
                <Image
                  className="rounded-lg object-cover"
                  width={"90%"}
                  height={"70%"}
                  layout="responsive"
                  src={web4}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://62dd6039509fb672a4dcc6d0--incandescent-faloodeh-f0a53c.netlify.app/">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"90%"}
                  layout="responsive"
                  src={web2}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://tangerine-kringle-64e68b.netlify.app">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"90%"}
                  layout="responsive"
                  src={web3}
                />
              </a>
            </div>
          </div>
        </section>  
      </main>
    </div>
  );
}
